CWR/CWR/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('CwrApp.urls'), name="Cwr_App"),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#               + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CWR/CwrApp/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views
from . import api
app_name = 'CwrApp'
router = DefaultRouter()
router.register(r'chat', api.MessagesAreaModelViewSet, basename='api-chats')
urlpatterns = [
   path('', views.index, name='index'),
   path('signup/', views.signupHandle, name='signup'),
   path('login/', views.loginHandle, name='login'),
   path('logout/', views.logoutHandle, name='login'),
   path('submit/', views.submit, name='submit'),
   path(r'api/', include(router.urls)),
]

CWR/CwrApp/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class MessagesArea(models.Model):
    sno = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    timeStamp = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.user.username

CWR/CwrApp/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib import messages

# Create your views here.
from .models import MessagesArea


def index(request):
    return render(request, "index.html")


def signupHandle(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']

        if (username or email or password) == "":
            messages.error(request, "username, email, password Should Not EMPTY.!")
            return redirect('index')
        elif not username.isalnum():
            messages.error(request, " User name should only contain letters and numbers")
            return redirect('../')
        elif User.objects.filter(username=username).exists():
            messages.error(request, "This name already taken try with Your nick name please.")
            return redirect("../")

        myuser = User.objects.create_user(username, email, password)
        myuser.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Your RChat Account created SuccessFully.!  ")
            return redirect("../")
        return redirect('../')

    else:
        return HttpResponse("404 Not Found")


def loginHandle(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Successfully locked IN..")
            return redirect("../")

        else:
            messages.error(request, 'Credential Error Please try again..')
            return redirect('../')


def logoutHandle(request):
    logout(request)
    messages.success(request, "Successfully LogOut..")
    return redirect("../")


def submit(request):
    if request.method == 'POST':
        mesage = request.POST.get('text')
        if mesage == "":
            messages.error(request, "Massege should not empty")
            return redirect("../")
        obj = MessagesArea.objects.create(user=request.user, message=mesage)
        return JsonResponse({
            'status': True,
            'message': obj.message,
            'timeStamp': obj.timeStamp
        })

    return JsonResponse({
        'status': False,
        'message': 'Invalid request'
    })

CWR/templates/index.html
<!doctype html>
<html lang="en">
{% load static %}
{% load humanize %}

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <title>Hello, world!</title>
  <style>
    body {
      background-color: #2F2F2F;
    }
  </style>
</head>

<body onload="loadMore()">
  <!--massage is here-->
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    <strong>Message : </strong> {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %}

  <div class="d-flex  ml-1">
    <div style="user-select: none;" class="">
      <img class="rounded-circle shadow-1-strong me-3 mr-2 mt-3" src="static\me.jpg" alt="avatar" width="60"
        height="60" />
    </div>
    <div class="mt-1">
      <h6 style="user-select: none;" class="fw-bold text-primary mb-1 mt-3">Rush-Wan</h6>
      <p style="user-select: none;" class="text-muted small mb-0 mt-3 user-select-none">
        This is like DISCORD but
        not equally same..!<br>
        You can ask me a question here.
      </p>

    </div>
  </div>
  <div class="row w-100 mt-2 container d-flex justify-content-center align-items-center">
    <!-- Here Is LogOut -->
    {% if user.is_authenticated %}
    <div class="mt-1">
      <a style="background-color: #2F2F2F;" href="logout/" class="btn">
        <img src="https://img.icons8.com/windows/50/000000/logout-rounded-down.png" />
      </a>
      <h6 class="text-light ml-2">LogOut</h6>
    </div>

    {% else %}

    <!-- Here is SignUp -->
    <!-- Button trigger modal -->
    <button style="background-color: #2F2F2F;" type="button" class="btn" data-toggle="modal"
      data-target="#exampleModalCenter">
      <div class="">
        <img src="https://img.icons8.com/dotty/80/000000/add-user-male.png" />
        <h6 class="ml-3 text-light mt-1">Sign Up</h6>
      </div>
    </button>
    <button style="background-color: #2F2F2F;" type="button" class="btn mx-1" data-toggle="modal" data-target="#LogIn">
      <div class="mt-4">
        <img src="https://img.icons8.com/ios-filled/50/000000/login-rounded-right.png" />
        <h6 class="ml-1 text-light mt-2">LogIn</h6>
      </div>
    </button>

    {% endif %}
  </div>




  <!-- Modal for signUp -->
  <!-- Button trigger modal -->
  <!-- Modal -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="signup/" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="username">Username</label>
              <input type="text" class="form-control" name="username" id="username" placeholder="Name">
            </div>
            <div class="form-group">
              <label for="email">Email</label>
              <input type="email" class="form-control" name="email" id="email" placeholder="Email">
            </div>
            <div class="form-group">
              <label for="password">Password</label>
              <input type="password" class="form-control" name="password" id="password" placeholder="Create Password">
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Create</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <!--instraction modal-->
  <!-- Button for instructions modal -->


<!-- Modal -->
<div class="modal fade" id="Instructions" tabindex="-1" role="dialog" aria-labelledby="Instructions" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="Instructions">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p class=""> <b>You need to signUp for post a message..</b></p>
        <img src="https://img.icons8.com/ios/50/000000/savouring-delicious-food-face--v2.png"/>
      </div>
      <div class="modal-footer">
        <!--<button type="button" class="btn btn-secondary" data-dismiss="modal">Ok</button>-->
         <button style="" type="button" class="btn" data-toggle="modal" data-dismiss="modal"
      data-target="#exampleModalCenter">
      <div class="">
        <img src="https://img.icons8.com/dotty/80/000000/add-user-male.png" />
        <h6  class="ml-3 text-light mt-1 text-dark">Sign Up</h6>
      </div>
    </button>
      </div>
    </div>
  </div>
</div>


  <!-- Modal for Login -->
  <div class="modal fade" id="LogIn" tabindex="-1" role="dialog" aria-labelledby="LogIn" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

          <form action="login/" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="formGroupExampleInput">Username</label>
              <input type="text" class="form-control" name="username" id="formGroupExampleInput" placeholder="Name">
            </div>
            <div class="form-group">
              <label for="formGroupExampleInput2">Password</label>
              <input type="password" class="form-control" name="password" id="formGroupExampleInput2"
                placeholder="Enter Password that was you create">

            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Login</button>
            </div>
          </form>



        </div>
      </div>
    </div>
  </div>

  <section style="background-color: 	#F1D82D;">
    <div class="container my-5 py-5">
      <div class="row d-flex justify-content-center">
        <div class="col-md-12 col-lg-10 col-xl-8">
          <div id="content-message-section">
            {% for object in objects %}
            <div class="card">
              <div class="card-body">
                <div class="d-flex flex-start align-items-center">
                  <img class="rounded-circle shadow-1-strong me-3 mr-2"
                    src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="avatar" width="60" height="60" />
                  <div>
                    <h6 id="{{object.sno}}" class="fw-bold text-primary mb-1">{{object.user.username}}</h6>
                    <p class="text-muted small mb-0">
                      Shared - {{object.timeStamp |naturaltime}}

                    </p>
                  </div>
                </div>

                <p class="mt-3 mb-4 pb-2">
                  {{object.message}}
                </p>
              </div>
            </div>
            {% endfor %}
          </div>


          <div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
            <button id="load-more-btn" class="btn btn-success my-3 p-2" onclick="loadMore()">Load more</button>
            <p id="no-chats" style="display: none;">No more chats</p>
            <div class="d-flex flex-start w-100">
              <img class="rounded-circle shadow-1-strong me-3 mr-2"
                src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="avatar" width="40" height="40" />
              <div class="form-outline w-100">
                <textarea class="form-control" id="value" rows="4" style="background: #fff;"></textarea>
                <label class="form-label" for="value"></label>
              </div>
            </div>
            {% if user.is_authenticated %}
            <div class="float-end mt-2 pt-1">
              <button type="submit" id="submit" class="btn btn-primary btn-sm">Post</button>
            </div>
            {% else %}
             <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Instructions">
                  Post
                </button>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    </div>
  </section>
  <div style="user-select: none;" class="row w-100 d-flex justify-content-center ">
    <img class="user-select-none" src="https://img.icons8.com/material-outlined/24/000000/instagram-new--v1.png" />
    <div class="">
      <p class="text-muted small mb-0 user-select-none">
        @rushwan07
      </p>
    </div>

  </div>

  <!-- <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script> -->


  <!-- Optional JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script> -->
  <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->

  <script>
    $('#submit').click(function () {
      var text = $('#value').val();
      let csrftoken = $('input[name=csrfmiddlewaretoken]').val();

      $.ajax({
        type: 'POST',
        url: "{% url 'CwrApp:submit' %}",
        dataType: 'json',
        data: {
          csrfmiddlewaretoken: csrftoken,
          'text': text
        },
        success: function (response) {
          if (response['status'] === true) {
            $("#content-message-section").prepend(`
              <div class="card">
            <div class="card-body">
              <div class="d-flex flex-start align-items-center">
                <img class="rounded-circle shadow-1-strong me-3 mr-2"
                  src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="avatar" width="60" height="60" />
                <div>
                  <h6 class="fw-bold text-primary mb-1">{{ user }}</h6>
                  <p class="text-muted small mb-0">
                    Shared - `+ response['timeStamp '] + `
                  </p>
                </div>
              </div>

              <p class="mt-3 mb-4 pb-2">
                `+ response['message'] + `
              </p>
            </div>
          </div>
              `);
          }
          $('#value').val("");
        },
        error: function (response) {
          console.log(response);
        }
      });
    });

    function loadMore() {
      var current_chats = $('#content-message-section').children('div').length;
      console.log(current_chats);
      let csrftoken = $('input[name=csrfmiddlewaretoken]').val();
      $.ajax({
        type: 'GET',
        url: window.location.origin + '/api/chat',
        dataType: 'json',
        data: {
          csrfmiddlewaretoken: csrftoken,
          'current_chats': current_chats
        },
        success: function (response) {
          if (response.length === 0) {
            $("#load-more-btn").css('display', 'none');
            $('#no-chats').css('display', 'block');
          }
          else {
            response.forEach(element => {
              $("#content-message-section").append(`
              <div class="card">
            <div class="card-body">
              <div class="d-flex flex-start align-items-center">
                <img class="rounded-circle shadow-1-strong me-3 mr-2"
                  src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="avatar" width="60" height="60" />
                <div>
                  <h6 class="fw-bold text-primary mb-1">`+ element.user + `</h6>
                  <p class="text-muted small mb-0">
                    Shared - `+ element.timeStamp+ `
                  </p>
                </div>
              </div>

              <p class="mt-3 mb-4 pb-2">
                `+ element.message + `
              </p>
            </div>
          </div>
              `);
            });
          }
        },
        error: function (response) {
          console.log(response);
        }
      });
    }
  </script>
</body>

</html>